### ISSUE TITLE
See what site looks like with grey background banner?

### ISSUE THREAD

**Issue by saraannwylie** [edgi-govdata-archiving/EEW-Website#160]
Just a thought but it might improve the look of the site not to have turquoise as the primary color particular for the blue and red reportcard page? Wondered how it would look with the EDGI grey color as the banner background? could still use turquoise for the text?
<img width="398" alt="Screen Shot 2020-10-04 at 4 08 45 PM" src="https://user-images.githubusercontent.com/8268933/95025987-fc52af80-065b-11eb-9ad9-2961080e55d7.png">

**Comment by Frijol** [comment]
I see what you mean, but I think/hope playing with the colors in the Reports section is a better solution. Changing the background color here creates some separate issues since we don't currently have a transparent version of our EEW logo

![Screen Shot 2020-10-06 at 8 51 36 AM](https://user-images.githubusercontent.com/454690/95225933-397c8600-07b1-11eb-889c-c07c1b163d99.png)

**Comment by Frijol** [comment]
Hm, actually here's a different take that would be perfectly fine (and, fixed image issue)

![Screen Shot 2020-10-06 at 9 04 15 AM](https://user-images.githubusercontent.com/454690/95227474-00451580-07b3-11eb-8244-78430bb999e9.png)

**Comment by saraannwylie** [comment]
I quite like the 2nd lighter grey, curious what other people think. Thanks for giving this a try @Frijol

**Comment by Frijol** [comment]
Here it is with new color scheme red

![Screen Shot 2020-10-07 at 1 30 34 PM](https://user-images.githubusercontent.com/454690/95384384-627c4400-08a1-11eb-879e-4498239fe952.png)

Vs green

![Screen Shot 2020-10-07 at 1 31 47 PM](https://user-images.githubusercontent.com/454690/95384440-79bb3180-08a1-11eb-8770-b5c6084fd8a7.png)


tbh I prefer the green but if folks in general have a strong preference for gray I'm ok switching to it
