### ISSUE TITLE
Modify snippet image

### ISSUE THREAD

**Issue by ericnost** [edgi-govdata-archiving/EEW-Website#253]
When we post a link to environmentalenforcemenwatch.org on social media, Slack, etc., we get what I think is the default Gatsby snippet / preview (a big G) See here:

https://twitter.com/EnviroDGI/status/1321195049745436673

Anyway we could change that to the EDGI or EEW logo?

**Comment by Frijol** [comment]
Good point. This looks like the right sort of thing: https://codeburst.io/how-to-automate-social-sharing-cards-on-your-gatsby-blog-77a356a58b38

**Comment by Frijol** [comment]
Hm. I made an attempt but I think it was not successful

**Comment by Frijol** [comment]
@shansen5 suggests replacing static/social.png, trying that

**Comment by Frijol** [comment]
sadly it didn't work. There's also https://medium.com/swlh/share-website-preview-images-in-gatsby-10cac58dd4d7 and various other ideas out there

**Comment by Frijol** [comment]
![Screen Shot 2021-03-18 at 12 11 53 PM](https://user-images.githubusercontent.com/454690/111683847-3915fb80-87e3-11eb-8b9a-cacb38ab6b92.png)
this is a weird thing I just noticed, wonder if it's related

**Comment by CaptainStack** [comment]
Oh hey - it looks like at some point this was updated because looking at the original Tweet that is linked in Eric's original post, I currently see the EEW logo:

![image](https://user-images.githubusercontent.com/1592484/139178107-c399b0da-180f-4a82-aae7-436db059022a.png)

I do know how to update these previews so I'm happy to do so if you like. My opinion on the current previews is that they are fine except that the image looks as if it was not specifically picked to be a social media preview as its dimensions are not really correct.
