### ISSUE TITLE
Add all congressional reports to website

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#309]

**Comment by ericnost** [comment]
A few thoughts and questions: what do we need in order to do this? Sounds like @CaptainStack and @shansen5 need to touch base on getting the JSON with all the links? Do we need to do any updating to the reports page structure itself?

**Comment by Frijol** [comment]
I've started a concept for this in a new branch called all-reports — we have the json from @shansen5 (thanks!). Essentially @CaptainStack will need to do a little modularization of the ReportCardExplorer component so that it's reusable between the 2020 committees work and the auto-updating all-congress reports. That's most of the technical side, which should come together pretty quickly I think.

Re information design, I'm thinking we'll have a tab called "Congressional District Reports" and also one called "2020 Congressional Committee Report Cards" or similar on the left sidebar of the Data site section, as a way of preserving the old work while bringing in the new.

That leaves us free to creatively design what else belongs on the new reports page in addition to the reports themselves. I'm thinking:
* The maps you've been working on (will they auto-update?)
* An explanation of what's interesting about analyzing at the LD level
* Methods, incl. how often the reports update

**Comment by ericnost** [comment]
For simplicity, might say "2021 Congressional District Report Cards" and "2020 Congressional District Report Cards" to signal the first edition, otherwise it might be unclear what the difference between reports and report cards is. I know the 2020 edition was just for select committee members, but that can be explained on that page?

Another thing to note is that the 2020 work actually mostly referred to 2019 numbers (because 2020 wasn't done at that point.) Just need to be consistent with which we choose.

Maps won't auto-update exactly, there's some processing that has to be done, but it's not particularly onerous. Easy to do once a year.

**Comment by Frijol** [comment]
Hm, we should talk—I thought the new reports were planned to auto-update regularly? @shansen5 can you clarify?

**Comment by ericnost** [comment]
reports can auto-update but not the maps I made, which require more manual post-processing

**Comment by Frijol** [comment]
Expected behavior of report card explorer on this page:

* Titles are "Senate" and "House"
* Chair/member/etc don't apply here because we're not representing committees, so no need to list them in the hover box or change the size of the cells

Other design questions:
* Order of display/layout?

**Comment by Frijol** [comment]
Working on layout/copy in https://docs.google.com/document/d/1e8kOrvxgXocz0SgKF76ziG7Dr1P_-6RqqD6ZEgiqu0E/edit#

**Comment by Frijol** [comment]
closed in https://github.com/edgi-govdata-archiving/EEW-Website/pull/325
