### ISSUE TITLE
Donation buttons not propagating to remote site

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/EEW-Website#48]
![Screen Shot 2020-09-03 at 2 07 14 PM](https://user-images.githubusercontent.com/454690/92167210-dd5bc600-edee-11ea-8075-b7ca4253f78a.png)

![Screen Shot 2020-09-03 at 2 08 42 PM](https://user-images.githubusercontent.com/454690/92167299-02e8cf80-edef-11ea-905f-7207da3cfebd.png)

 cc @ozzmotic

**Comment by plastichotsprings** [comment]
I removed the extra initialization in https://github.com/edgi-govdata-archiving/EEW-Website/commit/66a2c03f6dd28101d6f4865b1a9d5d97329cf31b but it's still not working. Maybe need to check the ActBlue account settings because the embed element is only allowed to be on certain domains. See here https://support.actblue.com/campaigns/working-with-contribution-forms/embeddable-forms-buttons-for-nonprofits/

**Comment by plastichotsprings** [comment]
Update, got someone to add the https://edgi-govdata-archiving.github.io/ domain to the allowed domains on the actblue page and it didn't work :/

**Comment by plastichotsprings** [comment]
Wait... it... works now? https://edgi-govdata-archiving.github.io/EEW-Website/

So confused, but closing the issue

**Comment by plastichotsprings** [comment]
Argh, okay actually, the donation buttons don't appear when you first go to the URL, but if you follow an internal link to, say, "Press" you'll see them. And then you'll still see them when you navigate BACK to the home page. Reopening the issue.

**Comment by Frijol** [comment]
@ozzmotic suggests we are doing this exactly right and someone will need to reach out to ActBlue for help to proceed

In meeting we took a temperature check & decided this is ok to deprioritize until after launch, so removing from the launch milestone

**Comment by Frijol** [comment]
I think this is ok now?
